<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание 2: библиотека Numpy и линейная алгебра. Решение


In [4]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [18]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.97809837 0.20575446 0.81582548 ... 0.09854905 0.13705551 0.50219771]
 [0.03570673 0.98498488 0.56109715 ... 0.56685053 0.50420276 0.677227  ]
 [0.46918372 0.81350589 0.16823026 ... 0.05338808 0.99760711 0.70270372]
 ...
 [0.77790574 0.97779572 0.00192374 ... 0.15215943 0.65124149 0.10577749]
 [0.08211015 0.94642963 0.13098001 ... 0.37098408 0.64289468 0.43312596]
 [0.6421011  0.55376084 0.49661325 ... 0.02621648 0.97016191 0.41269926]]
[[0.73808362 0.1902492  0.93196175 ... 0.98451438 0.74500658 0.1159569 ]
 [0.69681559 0.37278779 0.91894986 ... 0.01815532 0.13861168 0.86202822]
 [0.20918293 0.0457026  0.41408307 ... 0.23503297 0.55958134 0.29708758]
 ...
 [0.72908935 0.84229799 0.21138615 ... 0.79616074 0.35656694 0.5287514 ]
 [0.62153517 0.26505067 0.24600731 ... 0.68190396 0.92321556 0.08271418]
 [0.59374091 0.68188545 0.78628812 ... 0.37471605 0.06745529 0.34148816]]


In [0]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    c = [[0 for _ in range(len(a))] for _ in range(len(b[0]))]
    for i in range(len(a)):
        for j in range(len(b)):
            for k in range(len(a[0])):
                c[i][j] += a[i][k] * b[k][j]
    return c

In [0]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return a @ b

In [21]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 759 ms, sys: 3.64 ms, total: 762 ms
Wall time: 764 ms


In [22]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 901 µs, sys: 1.17 ms, total: 2.07 ms
Wall time: 5.69 ms


In [23]:
np.abs(np.array(M1) - M2).sum()

1.495337187407131e-11

### Задание 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость.

In [0]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    return np.cumsum(A) / np.arange(1, len(A)+1)

In [0]:
# функция без NumPy
def stupid_sec_av(A):
    S = [sum(A[:i+1])/(i+1) for i in range(len(A))]
    return S

In [5]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# вторая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10**3) 

%time S1 = stupid_sec_av(A)
%time S2 = sec_av(A)
# проверим корректность (последовательности должны совпадать, т.е. разность равна 0):
np.abs(S1 - S2).sum()

NameError: name 'stupid_sec_av' is not defined

NameError: name 'sec_av' is not defined

NameError: name 'S2' is not defined

### Задание 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [1]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    N = np.array(X[::-1])
    N[1::2] = a
    N[::2] = N[::2] ** 3
    return np.hstack((np.array(X) , N))

In [2]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    N = X[::-1]
    N[1::2] = [a for _ in range(len(N[1::2]))]
    N[::2] = [x**3 for x in N[::2]]
    return X + N

In [6]:
X = [i for i in range(10, 1000, 10)]
# здесь код должен быть эффективнее примерно в 20 раз. 
%time S1 = stupid_transformation(X)
%time S2 = transformation(X)
# проверим корректность:
np.abs(S1 - S2).sum()

Wall time: 1 ms
Wall time: 1.02 ms


0

Почему методы ***numpy*** оказываются эффективнее (можно гуглить)?

Что вы можете сказать о скорости вычислений в NumPy? Ответ обоснуйте.

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 4

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [31]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.14587666 0.60686058 0.54341206] [0.69522759 0.3485586  0.17901567]


In [0]:
def stupid_scalar_product(a,b):
    return sum([x * y for (x, y) in zip(a, b)])

In [0]:
def numpy_scalar_product(a,b):
    return a @ b

In [34]:
%time product_1 = stupid_scalar_product(a,b)
%time product_2 = numpy_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 25 µs, sys: 5 µs, total: 30 µs
Wall time: 35.5 µs
CPU times: user 20 µs, sys: 4 µs, total: 24 µs
Wall time: 28.8 µs


0.0